### ISSUE TITLE
Master not being rendered as on github

### ISSUE THREAD

**Issue by askans** [tomik23/leaflet-examples#14]
Dzień dobry

Love your examples, it makes it easy to understand how they work!
AND you created a nice html template for own map websites.

Unfortunately when downloading your master as a zip and launching it in my browser I do not get the content you have on github, meaning no navigation, no maps (see attached picture).

![Bildschirmfoto von 2021-05-24 10-30-05](https://user-images.githubusercontent.com/4079944/119319822-2ef8f900-bc7b-11eb-928c-b242356f5da8.png)

The maps in the folder can be displayed individually, but not in that nice frame you developed.

Any suggestion what I need to change in order to use your overall template for my own purposes aka website?

**Comment by tomik23** [comment]
Dzień dobry ;)

Unfortunately, you won't run the example this way, because I use `featch` to generate the menu and you need a server, but if you go to the individual examples, they work.

Yes I know this doesn't fix the problem but there is a workaround.
Hope you are using vscode. Take a look at this plugin [LiveServer](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer), it opens all html files that require a server.

**Comment by askans** [comment]
Dziękuję 

It helped to get a better understanding of the problem. Now I have to check a bit further, because I really like your "template" to show so many different maps.

Will come back when I am successful
