### ISSUE TITLE
More examples!

### ISSUE THREAD

**Issue by javimarsal** [tomik23/leaflet-examples#57]
Due to the message on your README file "Work in progress, Suggestions welcome." I bring you some ideas that you could add to this repo.

- The first one is using a plugin to group layers. In this repo (https://github.com/ismyrnow/leaflet-groupedlayercontrol) we can find a demo that brings to examples (basic and advanced).
- The second one could be adding markers with different shapes. In the documentation of leaflet we can find two types of markers, marker and circleMarker, so the idea is to add markers as triangles, squares, and more types of polygons. I don't if a plugin already exists. If not, I don't know if there's an alternative solution rather than using icons.
- And if you want, you can visit this website (https://leafletjs.com/SlavaUkraini/plugins.html) that contains more plugins to use in leaflet.

I hope this can help you to add more awesome examples to this project!
(P.S. Your examples are so good and helpful)

**Comment by tomik23** [comment]
Hi Javier
Thanks for the ideas. I try not to use plugins. Showing their use in my examples is pointless because if you want to know how to use them, just go to the given plugin and there you have an exact example. I try not to duplicate the existing examples, but to invent new ones that can replace just such plugins because, as we know, this is the best way to learn.

PS. As for the second example, maybe I will use the idea ;)
